.. Review the README on instructions to contribute.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name"  -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-DP0-Assemblies-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: Documentation for DP0.1 Style Guide
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. list-table:: Schedule and planned content of DP0 Delegate Assemblies
   :header-rows: 1

   * - Date (Fridays at 9am US Pacific)
     - First Hour Presentation Topic
     - Second Hour Breakouts Topics
     - Chair and Presenter(s)
   * - 2021-07-16
     - Introduction to DP0, and to the RSP's Notebook and Portal Aspects.
     - *Q&A with Rubin staff.* 
     - The Community Engagement Team (Melissa Graham)
   * - 2021-07-30
     - Querying Catalogs with TAP in the Notebook and Portal Aspects.
     - *Portal Q&A. Notebook Q&A. DP0 science topics.* 
     - The Community Engagement Team (Leanne Guy)
   * - 2021-08-13
     - no assembly (Rubin 2021 Project and Community Workshop)
     - 
     - 
   * - 2021-08-27
     - Image Query, Retrieval, and Display.
     - *How to use afwDisplay. Image type Q&A. DP0 science topics.*
     - The Community Engagement Team (Jeff Carlin)
   * - 2021-09-10
     - Using the Butler for Data Discovery.
     - *Butler Q&A. Gen3 for Gen2 Users. DP0 science topics.*
     - The Community Engagement Team (Alex Drlica-Wagner)
   * - 2021-09-24
     - *LSST Science Pipelines*
     - *Pipelines Q&A. DP0 science topics.*
     - Rubin Algorithms and Pipelines Team (Yusra AlSayyad) 
   * - 2021-10-08
     - *Data Visualization*
     - *Visualization packages Q&A. DP0 science topics.*
     - Rubin Commissioning Team (Keith Bechtol)
   * - 2021-10-22
     - *Image Processing*
     - *Algorithms Q&A. DP0 science topics.*
     - Rubin Camera Subsystem (Andrew Bradshaw) 
   * - 2021-11-05
     - *Source Detection and Measurement*
     - *Measurement algorithms Q&A. DP0 science topics.*
     - *TBD*
   * - 2021-11-19
     - *Fake Source Injection*
     - *Fake sources Q&A. DP0 science topics.*
     - *TBD*
   * - 2021-12-03
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-14
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-28
     - Special Session on DP0.1: A Half-Year In Review
     - *small group discussions for delegate feedback*
     - The Community Engagement Team
   * - 2022+, if desired
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
