.. Review the README on instructions to contribute.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name"  -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-DP0-Assemblies-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: Documentation for DP0.1 Style Guide
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. list-table:: Schedule and planned content of DP0 Delegate Assemblies
   :header-rows: 1

   * - Date (Fridays at 9am US Pacific)
     - First Hour Presentation Topic
     - Second Hour Breakouts Topics
     - Chair and Presenter(s)
   * - 2021-07-16
     - `Introduction to DP0, and to the RSP's Notebook and Portal Aspects. <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-16/5689>`_
     - General Q&A. Portal queries Q&A. Python learners. Lightcurves. Large scale structure (LSS).
     - The Community Engagement Team (Melissa Graham)
   * - 2021-07-30
     - `Querying Catalogs with TAP in the Notebook and Portal Aspects. <https://community.lsst.org/t/summary-delegate-assembly-fri-jul-30/5747>`_
     - LSS Working Group. Data visualization. General Q&A. Delegate "New Friends". Single-star lightcurves. 
     - The Community Engagement Team (Leanne Guy)
   * - 2021-08-13
     - no assembly (Rubin 2021 Project and Community Workshop)
     - 
     - 
   * - 2021-08-27
     - `Image Query, Retrieval, and Display. <https://community.lsst.org/t/summary-delegate-assembly-fri-aug-27/5845>`_
     - More fun with image display. 
     - The Community Engagement Team (Jeff Carlin)
   * - 2021-09-10
     - `Using the Butler for Data Discovery. <https://community.lsst.org/t/summary-delegate-assembly-fri-sep-10/5850>`_
     - More fun with the Butler. General Q&A. Delegate networking.
     - The Community Engagement Team (Alex Drlica-Wagner)
   * - 2021-09-24
     - `LSST Science Pipelines <https://community.lsst.org/t/summary-delegate-assembly-friday-september-24/5884>`_
     - Source detection and measurement. Supernovae. Resolved stellar populations. General Q&A.
     - Yusra AlSayyad (Rubin Algorithms and Pipelines Team)
   * - 2021-10-08
     - Data Visualization
     - *Visualization packages Q&A. DP0 science topics.*
     - Keith Bechtol (Rubin Commissioning Team)
   * - 2021-10-22
     - Image Processing
     - *Algorithms Q&A. DP0 science topics.*
     - Andrew Bradshaw (Rubin Camera Subsystem Team) 
   * - 2021-11-05
     - Delegate presenters: Louise Edwards and Kristen Larson.
     - *delegate working groups*
     - *TBD*
   * - 2021-11-19
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2021-12-03
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-14
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-28
     - Special Session on DP0.1: A Half-Year In Review
     - *small group discussions for delegate feedback*
     - The Community Engagement Team
   * - 2022+, if desired
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
