.. Review the README on instructions to contribute.
.. Static objects, such as figures, should be stored in the _static directory. Review the _static/README on instructions to contribute.
.. Do not remove the comments that describe each section. They are included to provide guidance to contributors.
.. Do not remove other content provided in the templates, such as a section. Instead, comment out the content and include comments to explain the situation. For example:
	- If a section within the template is not needed, comment out the section title and label reference. Do not delete the expected section title, reference or related comments provided from the template.
    - If a file cannot include a title (surrounded by ampersands (#)), comment out the title from the template and include a comment explaining why this is implemented (in addition to applying the ``title`` directive).

.. This is the label that can be used for cross referencing this file.
.. Recommended title label format is "Directory Name"-"Title Name"  -- Spaces should be replaced by hyphens.
.. _DP0-Delegate-Resources-DP0-Assemblies-Schedule:
.. Each section should include a label for cross referencing to a given area.
.. Recommended format for all labels is "Title Name"-"Section Name" -- Spaces should be replaced by hyphens.
.. To reference a label that isn't associated with an reST object such as a title or figure, you must include the link and explicit title using the syntax :ref:`link text <label-name>`.
.. A warning will alert you of identical labels during the linkcheck process.

.. This file does not contain a title because it is a table for another location (dp0-delegate-resources/index.rst).
.. title:: Documentation for DP0.1 Style Guide
.. ################################
.. DP0 Delegate Assemblies Schedule
.. ################################

.. This section should provide a brief, top-level description of the page.

.. list-table:: Schedule and planned content of DP0 Delegate Assemblies
   :header-rows: 1

   * - Date (Fridays at 9am US Pacific)
     - First Hour Presentation Topic
     - Second Hour Breakouts Topics
     - Chair and Presenter(s)
   * - 2021-07-16
     - The Rubin Vision and Roadmap for Data Preview 0
     - Demo "Intro to Jupyter Notebooks (NB) and DP0". Q&A for delegates with NB experience.
     - The Community Engagement Team
   * - 2021-07-30
     - Data Discovery with the Butler and the Portal
     - Butler Q&A. Portal Aspect Q&A. DP0 science.
     - The Community Engagement Team
   * - 2021-08-13
     - no assembly (Rubin 2021 Project and Community Workshop)
     - 
     - 
   * - 2021-08-27
     - Querying Catalogs via the Notebook and Portal Aspects.
     - Notebook Q&A. Portal Q&A. DP0 science. 
     - The Community Engagement Team
   * - 2021-09-10
     - Image Query, Retrieval, and Display.
     - Butler Q&A. Notebook Q&A. Image type Q&A. DP0 science.
     - The Community Engagement Team
   * - 2021-09-24
     - *LSST Science Pipelines*
     - *Pipeline Q&A.* DP0 science.
     - *TBD*
   * - 2021-10-08
     - *Data Visualization*
     - *Data vis package Q&A.* DP0 science.
     - *TBD*
   * - 2021-10-22
     - *Image Processing*
     - *Image algorithms Q&A.* DP0 science.
     - *TBD*
   * - 2021-11-05
     - *Source Detection and Measurement*
     - *Measurement algorithm Q&A.* DP0 science.
     - *TBD*
   * - 2021-11-19
     - *Fake Source Injection*
     - *Fake source Q&A.* DP0 science.
     - *TBD*
   * - 2021-12-03
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-14
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
   * - 2022-01-28
     - Special Session on DP0.1: A Half-Year In Review
     - *small group discussions for delegate feedback*
     - The Community Engagement Team
   * - 2022+, if desired
     - *delegate presenter(s)*
     - *delegate working groups*
     - *TBD*
